//Compromised Anydesk Certificate Usage
//https://anydesk.com/en/public-statement
//https://github.com/Neo23x0/signature-base/blob/master/yara/gen_anydesk_compromised_cert_feb23.yar

DeviceFileCertificateInfo
| where Timestamp >ago(90d)
| where CertificateSerialNumber =~ "0dbf152deaf0b981a8a938d53f769db8"
| where Issuer=~"DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1"
| where Signer !~ "Anydesk Software GmbH"
